# backend/app/services/clustering_service.py
import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler # For scaling latent features
import joblib # For saving the scaler
from typing import Dict, Any, Optional, Tuple, List, Union
import os
import json # For saving metadata

# Helper function to convert NumPy types to Python native types for JSON serialization
def convert_to_serializable(obj):
    """Convert NumPy types to Python native types for JSON serialization."""
    if isinstance(obj, (np.integer, np.int64, np.int32, np.int16, np.int8)):
        return int(obj)
    elif isinstance(obj, (np.floating, np.float64, np.float32, np.float16)):
        return float(obj)
    elif isinstance(obj, (np.ndarray,)):
        return obj.tolist()
    elif isinstance(obj, (np.bool_)):
        return bool(obj)
    elif isinstance(obj, dict):
        return {k: convert_to_serializable(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [convert_to_serializable(i) for i in obj]
    elif isinstance(obj, tuple):
        return tuple(convert_to_serializable(i) for i in obj)
    else:
        return obj

from app.config.config import get_settings # MODIFIED IMPORT
settings = get_settings() # Assuming settings is directly importable

# If get_settings is a function:
# from app.config.config import get_settings
# settings = get_settings()


def _get_clustering_artifact_path(
    base_path: str,
    dataset_id: int,
    user_id: int,
    artifact_name: str
) -> str:
    # Create a main "clustering" directory for this dataset
    # And then subdirectories for specific outputs if needed, or just dump files here.
    dir_path = os.path.join(base_path, f"user_{user_id}", f"dataset_{dataset_id}", "clustering_outputs") # Changed to "clustering_outputs"
    os.makedirs(dir_path, exist_ok=True)
    return os.path.join(dir_path, artifact_name)


class DBSCANService:
    def __init__(
        self,
        dataset_id: int,
        user_id: int,
        eps: float = 0.5,
        min_samples: int = 5, # Default, will be overridden by payload
        metric: str = 'euclidean',
    ):
        self.dataset_id = dataset_id
        self.user_id = user_id
        self.eps = eps
        self.min_samples = min_samples
        self.metric = metric
        
        self.cluster_model_sklearn = None # To store the fitted DBSCAN model
        self.fitted_scaler_ = None # To store the scaler for latent features

        self.ARTIFACT_BASE = settings.OUTLIER_ARTIFACTS_BASE_PATH
        
        # Define paths for artifacts generated by this service
        self.clustering_metadata_path = _get_clustering_artifact_path(
            self.ARTIFACT_BASE, dataset_id, user_id, "clustering_metadata.json"
        )
        self.cluster_labels_save_path = _get_clustering_artifact_path(
             self.ARTIFACT_BASE, dataset_id, user_id, "cluster_labels.parquet"
        )
        self.latent_features_scaler_path = _get_clustering_artifact_path(
            self.ARTIFACT_BASE, dataset_id, user_id, "latent_features_scaler.joblib"
        )


    def perform_dbscan_clustering(self, features_df: pd.DataFrame) -> Tuple[pd.Series, Dict[str, Any]]:
        """
        Performs DBSCAN clustering on the provided features.
        Features are scaled (StandardScaler) before clustering.
        Saves cluster labels, metadata, and the scaler used.
        Adaptively adjusts DBSCAN parameters if too many noise points are detected.
        """
        if not isinstance(features_df, pd.DataFrame) or features_df.empty:
            raise ValueError("CLUSTERING_SERVICE: Input features_df must be a non-empty Pandas DataFrame.")
        
        # Ensure all columns are numeric (DBSCAN requires numerical input)
        if not all(features_df.dtypes.apply(pd.api.types.is_numeric_dtype)):
            non_numeric_cols = features_df.columns[~features_df.dtypes.apply(pd.api.types.is_numeric_dtype)].tolist()
            raise ValueError(f"CLUSTERING_SERVICE: All input features for DBSCAN must be numeric. Non-numeric columns found: {non_numeric_cols}")

        # Handle NaNs - CRITICAL for both scaler and DBSCAN
        if features_df.isnull().values.any():
            print(f"CLUSTERING_SERVICE: Warning - NaNs found in {features_df.isnull().sum().sum()} cells for clustering. Imputing with column means.")
            # Impute NaNs using column means. This is a simple strategy.
            # Consider if a more sophisticated imputation was done upstream or is needed.
            for col in features_df.columns[features_df.isnull().any()]:
                features_df[col] = features_df[col].fillna(features_df[col].mean())
            # If any column was entirely NaN, its mean would be NaN. Fill those with 0.
            if features_df.isnull().values.any():
                print("CLUSTERING_SERVICE: Warning - NaNs persist after mean imputation (likely all-NaN columns). Filling with 0.")
                features_df = features_df.fillna(0)


        print(f"CLUSTERING_SERVICE: Performing DBSCAN for dataset {self.dataset_id}, user {self.user_id}...")
        print(f"Original DBSCAN params: eps={self.eps}, min_samples={self.min_samples}, metric={self.metric}")
        print(f"Input features shape before scaling: {features_df.shape}")

        # 1. Scale the latent features
        scaler = StandardScaler()
        try:
            # Ensure we are working with a NumPy array for scaling
            scaled_feature_values = scaler.fit_transform(features_df.values)
            self.fitted_scaler_ = scaler # Store the fitted scaler instance
            joblib.dump(self.fitted_scaler_, self.latent_features_scaler_path)
            print(f"CLUSTERING_SERVICE: Latent features scaled. Scaler saved to {self.latent_features_scaler_path}")
        except Exception as e:
            print(f"CLUSTERING_SERVICE: Error during feature scaling: {e}")
            raise

        # 2. Perform DBSCAN on scaled features with adaptive parameter adjustment
        max_attempts = 3  # Maximum number of attempts to adjust parameters
        current_eps = self.eps
        current_min_samples = self.min_samples
        
        # Set a more moderate noise threshold - we want to reduce noise but still allow some
        # to ensure we're capturing potential outliers
        noise_threshold = 0.3  # If more than 30% of points are noise, try to adjust parameters
        
        for attempt in range(max_attempts):
            print(f"CLUSTERING_SERVICE: Attempt {attempt+1}/{max_attempts} - DBSCAN with eps={current_eps}, min_samples={current_min_samples}")
            
            dbscan = DBSCAN(eps=current_eps, min_samples=current_min_samples, metric=self.metric, n_jobs=-1)
            
            try:
                cluster_labels_np = dbscan.fit_predict(scaled_feature_values)
                
                # Calculate noise percentage
                num_noise = int(np.sum(cluster_labels_np == -1))
                total_points = len(cluster_labels_np)
                noise_percentage = num_noise / total_points if total_points > 0 else 0
                
                print(f"CLUSTERING_SERVICE: DBSCAN found {num_noise}/{total_points} noise points ({noise_percentage:.2%})")
                
                # If noise percentage is acceptable or we've reached max attempts, use these results
                if noise_percentage < noise_threshold or attempt == max_attempts - 1:
                    break
                
                # Otherwise, adjust parameters for next attempt
                # Increase eps to create larger clusters
                current_eps *= 1.5
                # Decrease min_samples to make it easier to form clusters
                current_min_samples = max(3, int(current_min_samples * 0.7))
                
                print(f"CLUSTERING_SERVICE: Too many noise points. Adjusting parameters for next attempt.")
                
            except MemoryError as me:
                print(f"CLUSTERING_SERVICE: MemoryError during DBSCAN fit_predict: {me}. ")
                print("This often happens with large N, or if 'eps' is too large / 'min_samples' too small for the data density.")
                print("Consider adjusting DBSCAN parameters, especially increasing 'min_samples' and tuning 'eps' for the scaled data.")
                raise  # Re-raise the memory error to be caught by the orchestrator
            except Exception as e:
                print(f"CLUSTERING_SERVICE: Error during DBSCAN fit_predict: {e}")
                raise

        self.cluster_model_sklearn = dbscan # Store the fitted DBSCAN model

        # Create a Series for cluster labels, using the original DataFrame's index
        cluster_labels_series = pd.Series(cluster_labels_np, index=features_df.index, name="cluster_label")
        
        # Calculate number of clusters and noise points
        unique_labels = set(cluster_labels_np)
        num_clusters = len(unique_labels) - (1 if -1 in unique_labels else 0)
        num_noise = int(np.sum(cluster_labels_np == -1))
        
        print(f"CLUSTERING_SERVICE: DBSCAN completed. Clusters found: {num_clusters}, Noise points: {num_noise}")
        
        # 3. Save metadata
        metadata = {
            "algorithm": "DBSCAN",
            "params_input": {"eps": self.eps, "min_samples": self.min_samples, "metric": self.metric},
            "input_features_shape": list(features_df.shape),
            "scaled_features_shape": list(scaled_feature_values.shape),
            "num_clusters_found": num_clusters,
            "num_noise_points": num_noise,
            "artifacts": {
                "labels_path": self.cluster_labels_save_path,
                "metadata_path": self.clustering_metadata_path,
                "latent_features_scaler_path": self.latent_features_scaler_path
            }
        }
        try:
            with open(self.clustering_metadata_path, 'w') as f:
                json.dump(metadata, f, indent=4)
            print(f"CLUSTERING_SERVICE: Clustering metadata saved to {self.clustering_metadata_path}")
        except IOError as e:
            print(f"CLUSTERING_SERVICE: Error saving clustering metadata: {e}") # Log but don't necessarily fail task

        # 4. Save cluster labels
        try:
            cluster_labels_df_to_save = cluster_labels_series.to_frame()
            cluster_labels_df_to_save.to_parquet(self.cluster_labels_save_path)
            print(f"CLUSTERING_SERVICE: Cluster labels saved to {self.cluster_labels_save_path}")
        except IOError as e:
            print(f"CLUSTERING_SERVICE: Error saving cluster labels: {e}")
            # Depending on severity, you might want to raise an error here or just log it

        return cluster_labels_series, metadata
    

    def get_artifact_paths(self) -> dict:
        """Returns paths to artifacts generated by this service, if they exist."""
        return {
            "clustering_metadata_path": self.clustering_metadata_path if os.path.exists(self.clustering_metadata_path) else None,
            "cluster_labels_path": self.cluster_labels_save_path if os.path.exists(self.cluster_labels_save_path) else None,
            "latent_features_scaler_path": self.latent_features_scaler_path if os.path.exists(self.latent_features_scaler_path) else None,
        }


def run_dbscan_clustering(df: pd.DataFrame, parameters: dict, true_labels=None) -> dict:
    """
    Wrapper function to run DBSCAN clustering on a DataFrame.
    
    Args:
        df: DataFrame to cluster
        parameters: Dictionary of parameters for DBSCAN
        
    Returns:
        Dictionary with clustering results, evaluation metrics, and visualizations
    """
    # Extract parameters
    eps = parameters.get('eps', 0.5)
    min_samples = parameters.get('min_samples', 5)
    metric = parameters.get('metric', 'euclidean')
    
    # Create a temporary service instance
    # Using 0 for dataset_id and user_id as they're not used for plotting
    service = DBSCANService(
        dataset_id=0,
        user_id=0,
        eps=eps,
        min_samples=min_samples,
        metric=metric
    )
    
    # Run clustering
    cluster_labels, metadata = service.perform_dbscan_clustering(df)
    
    # Add cluster labels to the DataFrame
    df_with_clusters = df.copy()
    df_with_clusters['cluster'] = cluster_labels
    
    # Calculate evaluation metrics
    from sklearn import metrics
    
    # Only calculate silhouette score if there's more than one cluster and no noise points (-1)
    silhouette_score = None
    if len(set(cluster_labels)) > 1 and -1 not in cluster_labels:
        try:
            silhouette_score = metrics.silhouette_score(df, cluster_labels)
        except:
            silhouette_score = None
    
    # Calculate Davies-Bouldin index if there's more than one cluster
    davies_bouldin_score = None
    if len(set(cluster_labels)) > 1 and -1 not in cluster_labels:
        try:
            davies_bouldin_score = metrics.davies_bouldin_score(df, cluster_labels)
        except:
            davies_bouldin_score = None
            
    # Calculate supervised metrics if true labels are provided
    f1_score = None
    precision_score = None
    recall_score = None
    accuracy_score = None
    
    if true_labels is not None:
        # For clustering evaluation with ground truth, we need to handle label matching
        # since cluster labels might not match true labels numerically
        from sklearn.metrics import accuracy_score, f1_score as f1, precision_score as precision, recall_score as recall
        from sklearn.metrics.cluster import contingency_matrix
        from scipy.optimize import linear_sum_assignment
        import numpy as np
        
        try:
            # Create contingency matrix
            contingency = contingency_matrix(true_labels, cluster_labels)
            # Find optimal one-to-one mapping between cluster labels and true labels
            row_ind, col_ind = linear_sum_assignment(-contingency)
            
            # Create a mapping from cluster labels to true labels
            cluster_to_true = {}
            unique_clusters = np.unique(cluster_labels)
            for i, cluster in enumerate(unique_clusters):
                if cluster != -1:  # Skip noise points
                    idx = np.where(unique_clusters == cluster)[0][0]
                    if idx < len(row_ind):
                        cluster_to_true[cluster] = col_ind[idx]
            
            # Map cluster labels to matched true labels
            mapped_labels = np.array([cluster_to_true.get(label, -1) for label in cluster_labels])
            
            # Calculate metrics (ignoring noise points)
            mask = cluster_labels != -1
            if np.any(mask):
                accuracy_score = accuracy_score(true_labels[mask], mapped_labels[mask])
                precision_score = precision(true_labels[mask], mapped_labels[mask], average='weighted')
                recall_score = recall(true_labels[mask], mapped_labels[mask], average='weighted')
                f1_score = f1(true_labels[mask], mapped_labels[mask], average='weighted')
        except Exception as e:
            print(f"Error calculating supervised metrics: {e}")
            # Keep metrics as None if calculation fails
    
    # Calculate cluster statistics
    unique_labels = set(cluster_labels)
    n_clusters = len(unique_labels) - (1 if -1 in unique_labels else 0)
    n_noise = list(cluster_labels).count(-1) if -1 in unique_labels else 0
    cluster_sizes = {label: list(cluster_labels).count(label) for label in unique_labels if label != -1}
    
    # Generate enhanced visualizations
    import matplotlib.pyplot as plt
    from matplotlib.figure import Figure
    import matplotlib.cm as cm
    import tempfile
    import io
    import base64
    from sklearn.decomposition import PCA
    
    # Create visualization paths
    scatter_plot_path = None
    distribution_plot_path = None
    pca_plot_path = None
    
    # 1. Basic scatter plot for the first two dimensions
    if df.shape[1] >= 2:
        fig = Figure(figsize=(10, 8))
        ax = fig.add_subplot(111)
        
        x_col, y_col = df.columns[0], df.columns[1]
        scatter = ax.scatter(df[x_col], df[y_col], c=cluster_labels, cmap='viridis', alpha=0.6)
        ax.set_xlabel(x_col)
        ax.set_ylabel(y_col)
        ax.set_title(f'DBSCAN Clustering (eps={eps}, min_samples={min_samples})')
        fig.colorbar(scatter, ax=ax, label='Cluster')
        
        # Save the plot to a temporary file
        with tempfile.NamedTemporaryFile(delete=False, suffix='.png') as tmp:
            scatter_plot_path = tmp.name
            fig.savefig(scatter_plot_path)
    
    # 2. Cluster size distribution plot
    if n_clusters > 0:
        fig = Figure(figsize=(10, 6))
        ax = fig.add_subplot(111)
        
        cluster_labels_list = [label for label in unique_labels if label != -1]
        cluster_sizes_list = [cluster_sizes[label] for label in cluster_labels_list]
        
        bars = ax.bar(cluster_labels_list, cluster_sizes_list, color='skyblue')
        ax.set_xlabel('Cluster')
        ax.set_ylabel('Number of Points')
        ax.set_title('Cluster Size Distribution')
        
        # Add the exact count on top of each bar
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height}',
                        xy=(bar.get_x() + bar.get_width() / 2, height),
                        xytext=(0, 3),  # 3 points vertical offset
                        textcoords="offset points",
                        ha='center', va='bottom')
        
        with tempfile.NamedTemporaryFile(delete=False, suffix='.png') as tmp:
            distribution_plot_path = tmp.name
            fig.savefig(distribution_plot_path)
    
    # 3. PCA visualization for high-dimensional data
    if df.shape[1] > 2:
        # Apply PCA to reduce to 2 dimensions for visualization
        pca = PCA(n_components=2)
        pca_result = pca.fit_transform(df)
        
        fig = Figure(figsize=(10, 8))
        ax = fig.add_subplot(111)
        
        scatter = ax.scatter(pca_result[:, 0], pca_result[:, 1], c=cluster_labels, cmap='viridis', alpha=0.6)
        ax.set_xlabel('Principal Component 1')
        ax.set_ylabel('Principal Component 2')
        ax.set_title(f'PCA Visualization of DBSCAN Clusters (eps={eps}, min_samples={min_samples})')
        fig.colorbar(scatter, ax=ax, label='Cluster')
        
        # Add explained variance ratio
        explained_variance = pca.explained_variance_ratio_
        ax.text(0.02, 0.98, f'Explained variance: PC1={explained_variance[0]:.2f}, PC2={explained_variance[1]:.2f}',
                transform=ax.transAxes, verticalalignment='top')
        
        with tempfile.NamedTemporaryFile(delete=False, suffix='.png') as tmp:
            pca_plot_path = tmp.name
            fig.savefig(pca_plot_path)
    
    # Create a summary of the analysis
    analysis_summary = {
        "algorithm": "DBSCAN",
        "parameters": {
            "eps": eps,
            "min_samples": min_samples,
            "metric": metric
        },
        "results": {
            "n_clusters": n_clusters,
            "n_noise_points": n_noise,
            "cluster_sizes": cluster_sizes,
            "data_shape": df.shape
        },
        "evaluation": {
            "silhouette_score": silhouette_score,
            "davies_bouldin_score": davies_bouldin_score,
            "f1_score": f1_score,
            "precision_score": precision_score,
            "recall_score": recall_score,
            "accuracy_score": accuracy_score
        }
    }
    
    # Convert all NumPy types to Python native types for JSON serialization
    analysis_summary = convert_to_serializable(analysis_summary)
    
    # Convert absolute file paths to URL paths for visualization images
    def convert_to_url_path(file_path):
        if file_path is None:
            return None
        # For Windows paths, extract just the filename
        import os
        filename = os.path.basename(file_path)
        return f"/tmp/{filename}"
    
    # Return enhanced results
    result = {
        "clustered_data": df_with_clusters,
        "n_clusters": n_clusters,
        "cluster_labels": cluster_labels.tolist(),
        "analysis_summary": analysis_summary,
        "visualizations": {
            "scatter_plot_path": convert_to_url_path(scatter_plot_path),
            "distribution_plot_path": convert_to_url_path(distribution_plot_path),
            "pca_plot_path": convert_to_url_path(pca_plot_path) if df.shape[1] > 2 else None
        }
    }
    
    # Convert any remaining NumPy types in the result
    return convert_to_serializable(result)