"""add_new_columns_correctly_v6

Revision ID: af196eaa7ec1
Revises: 394691225f23
Create Date: 2025-05-20 20:22:45.763481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af196eaa7ec1'
down_revision: Union[str, None] = '394691225f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outlier_detection_runs', sa.Column('clustering_latent_features_scaler_path', sa.String(), nullable=True))
    op.add_column('outlier_detection_runs', sa.Column('evaluation_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outlier_detection_runs', 'evaluation_metrics')
    op.drop_column('outlier_detection_runs', 'clustering_latent_features_scaler_path')
    # ### end Alembic commands ###
