"""add transformation_runs table

Revision ID: ff91a2b926bd
Revises: af196eaa7ec1
Create Date: 2025-06-05 23:02:29.251875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff91a2b926bd'
down_revision: Union[str, None] = 'af196eaa7ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transformation_runs_id', table_name='transformation_runs')
    op.drop_table('transformation_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformation_runs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transformed_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transformed_file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transformation_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='transformation_runs_dataset_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transformation_runs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transformation_runs_pkey')
    )
    op.create_index('ix_transformation_runs_id', 'transformation_runs', ['id'], unique=False)
    # ### end Alembic commands ###
