"""add_missing_columns_to_outlier_detection_runs

Revision ID: 394691225f23
Revises: f02715a782ef
Create Date: 2025-05-15 21:12:07.539908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '394691225f23'
down_revision: Union[str, None] = 'f02715a782ef' # This should be the ID of the migration file BEFORE this one
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - START ###
    # Note: The autogenerated part for 'datasets' and 'outlier_detection_runs' column additions
    # seemed correct based on your model for adding missing columns and changing JSON to JSONB.
    # The main fix is for the 'users.role' alteration.

    op.alter_column('datasets', 'format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('datasets', 'missing_values',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'data_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'categorical_issues',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'summary_stats',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'analysis_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False) # This makes user_id NOT NULL

    # Adding columns to outlier_detection_runs
    op.add_column('outlier_detection_runs', sa.Column('cluster_labels_path', sa.String(), nullable=True))
    op.add_column('outlier_detection_runs', sa.Column('scatter_plot_pca_path', sa.String(), nullable=True))
    op.add_column('outlier_detection_runs', sa.Column('num_numerical_features_used', sa.Integer(), nullable=True))
    op.add_column('outlier_detection_runs', sa.Column('num_clusters_found', sa.Integer(), nullable=True))
    op.add_column('outlier_detection_runs', sa.Column('num_noise_points', sa.Integer(), nullable=True))
    
    # Handling outlier_details vs outlier_results
    # This will add 'outlier_results' and drop 'outlier_details'.
    # If 'outlier_details' had data, it will be lost.
    # If you need to preserve data, you'd do an op.alter_column to rename 'outlier_details' to 'outlier_results'.
    # For now, assuming drop/add is okay as per autogenerate.
    op.add_column('outlier_detection_runs', sa.Column('outlier_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('outlier_detection_runs', 'outlier_details') # This was in your autogenerated script

    op.alter_column('outlier_detection_runs', 'status',
               existing_type=sa.VARCHAR(), # Assuming it was VARCHAR
               nullable=False) # This makes status NOT NULL

    # --- MODIFIED SECTION for users.role ---
    # Define the new ENUM type object that SQLAlchemy understands
    new_user_role_enum = sa.Enum('ADMIN', 'USER', name='user_role_enum_models', create_type=True)
    # Define the old ENUM type object if needed for existing_type, assuming it was named 'userrole'
    old_user_role_enum = postgresql.ENUM('ADMIN', 'USER', name='userrole', create_type=False)

    # Attempt to create the new ENUM type in PostgreSQL if it doesn't exist
    # This is often handled by SQLAlchemy when create_type=True is used with sa.Enum,
    # but for explicit control with Alembic and existing types, it can be done like this:
    # bind = op.get_bind()
    # if bind.dialect.name == 'postgresql':
    #    new_user_role_enum.create(bind, checkfirst=True)
    # Using create_type=True in the sa.Enum definition below should generally handle this.

    op.alter_column('users', 'role',
               existing_type=old_user_role_enum, # What Alembic detected as existing type
               type_=new_user_role_enum,         # The new type definition from your model
               existing_nullable=True,           # Keep as detected by Alembic
               postgresql_using='role::text::user_role_enum_models') # The CRUCIAL cast
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Define the enum types for downgrade clarity
    new_user_role_enum_for_downgrade = sa.Enum('ADMIN', 'USER', name='user_role_enum_models')
    old_user_role_enum_for_downgrade = postgresql.ENUM('ADMIN', 'USER', name='userrole')

    op.alter_column('users', 'role',
               existing_type=new_user_role_enum_for_downgrade, # Downgrading from this
               type_=old_user_role_enum_for_downgrade,         # To this old type
               existing_nullable=True,
               postgresql_using='role::text::userrole') # Cast back if needed

    # Revert outlier_detection_runs changes
    op.add_column('outlier_detection_runs', sa.Column('outlier_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('outlier_detection_runs', 'outlier_results')
    
    op.alter_column('outlier_detection_runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True) # Revert to nullable=True if that was original

    op.drop_column('outlier_detection_runs', 'num_noise_points')
    op.drop_column('outlier_detection_runs', 'num_clusters_found')
    op.drop_column('outlier_detection_runs', 'num_numerical_features_used')
    op.drop_column('outlier_detection_runs', 'scatter_plot_pca_path')
    op.drop_column('outlier_detection_runs', 'cluster_labels_path')

    # Revert datasets changes
    op.alter_column('datasets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True) # Revert to nullable=True if that was original
    op.alter_column('datasets', 'analysis_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'summary_stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'categorical_issues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'data_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'missing_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('datasets', 'format',
               existing_type=sa.VARCHAR(),
               nullable=False) # Revert to nullable=False if that was original
    # ### end Alembic commands ###