"""add feature_sets table for user-named feature engineering outputs

Revision ID: 682dc1602c8b
Revises: ff91a2b926bd
Create Date: 2025-06-19 01:09:01.395721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '682dc1602c8b'
down_revision: Union[str, None] = 'ff91a2b926bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_sets_id', table_name='feature_sets')
    op.drop_table('feature_sets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_sets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', postgresql.ENUM('AUTOENCODER', 'PCA', 'ISOMAP', name='feature_type_enum'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='feature_sets_dataset_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='feature_sets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feature_sets_pkey')
    )
    op.create_index('ix_feature_sets_id', 'feature_sets', ['id'], unique=False)
    # ### end Alembic commands ###
